name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main # This will trigger on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username is automatically available
          password: ${{ secrets.GTOKEN }}  # GitHub Actions token

      # Build the Docker image from the src directory and tag it for GHCR
      - name: Build and Tag Docker Image for GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/texnologia_logismikoy:${{ github.sha }} ./src
          docker tag ghcr.io/${{ github.repository_owner }}/texnologia_logismikoy:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/myapp:latest

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/texnologia_logismikoy:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/texnologia_logismikoy:latest
